version: "3.3"
services:
  db:
    image: mysql
    container_name: ecommerce_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: ecommerce_data
        target: /var/lib/mysql
volumes:
  ecommerce_data: